from sqlalchemy.orm import Session

from app.db.repositories.jd_repo import JDRepository
from app.db.repositories.resume_repo import ResumeRepository
from app.db.repositories.revision_repo import RevisionRepository
from app.llm.chains.resume_rewrite_chain import rewrite_resume


class ResumeService:
    def __init__(self, db: Session):
        self.jd_repo = JDRepository(db)
        self.resume_repo = ResumeRepository(db)
        self.revision_repo = RevisionRepository(db)

    def rewrite(self, jd_id: int, resume_content: str):
        jd = self.jd_repo.get(jd_id)
        if not jd:
            raise ValueError("JD not found")

        resume = self.resume_repo.create(resume_content)
        rewritten = rewrite_resume(jd.content, resume_content)
        revision = self.revision_repo.create(
            job_description_id=jd_id,
            resume_id=resume.id,
            revised_content=rewritten.get("revised_content", resume_content),
            rationale=rewritten.get("rationale", "Generated by LLM"),
        )
        return revision
